# docker-compose example
version: "3.3"

services:

  nginx:
    image: niiknow/nginx-image-proxy
    container_name: nginx-image-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
#      - "./data:/app:rw"
      - "./sites-enabled:/app/etc/nginx/sites-enabled:rw"
    ulimits:
      nproc: 65535
      nofile:
        soft: 200000
        hard: 400000
    sysctls:
      net.core.somaxconn: '2048'
    labels:
      - "Nginx Image Proxy"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "10"
